<?php

namespace WlSdk\Wl\User\Tracking;

class UserTrackerPutRequest
{
    /**
     * Business key.
     *
     * Primary key in RsBusinessSql table.
     *
     * @var string|null
     */
    public ?string $k_business = null;

    /**
     * Session ID to track with.
     * Its value is autogenerated when we call flow start method.
     *
     * @var string|null
     */
    public ?string $s_id = null;

    /**
     * Current step number.
     * `null` if the number of steps is not set or should not be updated.
     *
     * @var int|null
     */
    public ?int $i_step = null;

    /**
     * Total number of steps.
     * `null` if the number of steps is not set or should not be updated.
     *
     * @var int|null
     */
    public ?int $i_step_all = null;

    /**
     * Step of the flow, that the user is now on.
     *
     * @var string|null
     */
    public ?string $s_step = null;

    public function params(): array
    {
        return array_filter(
            [
            'k_business' => $this->k_business,
            's_id' => $this->s_id,
            'i_step' => $this->i_step,
            'i_step_all' => $this->i_step_all,
            's_step' => $this->s_step,
            ],
            static fn ($v) => $v !== null
        );
    }
}
