<?php

namespace WlSdk\Wl\User\Tracking;

class UserTrackerGetRequest
{
    /**
     * Business key.
     *
     * Primary key in RsBusinessSql table.
     *
     * @var string|null
     */
    public ?string $k_business = null;

    /**
     * Session ID to track with.
     * Its value is autogenerated when we call flow start method.
     *
     * @var string|null
     */
    public ?string $s_id = null;

    /**
     * Screen resolution in form of width x length.
     * Example: 1024x678.
     *
     * @var string|null
     */
    public ?string $s_resolution = null;

    public function params(): array
    {
        return array_filter(
            [
            'k_business' => $this->k_business,
            's_id' => $this->s_id,
            's_resolution' => $this->s_resolution,
            ],
            static fn ($v) => $v !== null
        );
    }
}
