<?php

namespace WlSdk\Wl\User\Tracking;

/**
 * Response from POST
 */
class UserTrackerPostResponse
{
    /**
     * Session ID to track with.
     * Its value is autogenerated when we call flow start method.
     *
     * @var string|null
     */
    public ?string $s_id = null;

    public function __construct(array $data)
    {
        $this->s_id = isset($data['s_id']) ? (string)$data['s_id'] : null;
    }
}
