<?php

namespace WlSdk\Wl\User\Tracking;

class UserTrackerPostRequest
{
    /**
     * Business key.
     *
     * Primary key in RsBusinessSql table.
     *
     * @var string|null
     */
    public ?string $k_business = null;

    /**
     * Session ID to track with.
     * Its value is autogenerated when we call flow start method.
     *
     * @var string|null
     */
    public ?string $s_id = null;

    /**
     * Screen resolution in form of width x length.
     * Example: 1024x678.
     *
     * @var string|null
     */
    public ?string $s_resolution = null;

    /**
     * Tracked user flow ID.
     * Constant from {@link \WlSdk\Wl\User\Tracking\FlowSid}.
     *
     * @var int|null
     * @see \WlSdk\Wl\User\Tracking\FlowSid
     */
    public ?int $id_flow = null;

    /**
     * Flag indicating the end of tracking.
     *
     * @var bool|null
     */
    public ?bool $is_end = null;

    /**
     * Flag indicating the start of tracking.
     *
     * @var bool|null
     */
    public ?bool $is_start = null;

    /**
     * Step of the flow, that the user is now on.
     *
     * @var string|null
     */
    public ?string $s_step = null;

    public function params(): array
    {
        return array_filter(
            [
            'k_business' => $this->k_business,
            's_id' => $this->s_id,
            's_resolution' => $this->s_resolution,
            'id_flow' => $this->id_flow,
            'is_end' => $this->is_end,
            'is_start' => $this->is_start,
            's_step' => $this->s_step,
            ],
            static fn ($v) => $v !== null
        );
    }
}
