<?php
namespace WlSdk\Wl\AiAgent\Link;

use WlSdk\WlSdkClient;

/**
 * Sends an AI agent link action email (booking or purchase) to the specified user.
 */
class SendMailApi
{
    /**
     * Purchase item ID. Required if `text_action` is 'purchase'.
     * 
     * One of the [RsPurchaseItemSid](#/components/schemas/RsPurchaseItemSid) constants.
     *
     * @var int|null
     */
    public ?int $id_purchase_item = null;

    /**
     * Service ID. Required if `text_action` is 'booking'.
     *
     * @var int|null
     */
    public ?int $id_service = null;

    /**
     * Business key. Required.
     *
     * @var string|null
     */
    public ?string $k_business = null;

    /**
     * Unique identifier for the link.
     *
     * @var string|null
     */
    public ?string $k_id = null;

    /**
     * Action type. Must be 'purchase' or 'booking'.
     *
     * @var string|null
     */
    public ?string $text_action = null;

    /**
     * User ID. Required.
     *
     * @var string|null
     */
    public ?string $uid = null;

    /** @var WlSdkClient */
    private $client;

    public function __construct(WlSdkClient $client)
    {
        $this->client = $client;
    }

    /**
     * Sends an AI agent link action email (booking or purchase) to the specified user.
     *
     * Triggers the email that the AI agent sends when a client clicks a booking or purchase link
     *  generated by the AI agent chat. Requires the business to have an active AI agent subscription;
     *  the action type determines which notification template is used and which service or purchase
     *  item is referenced in the email body.
     *
     * @return SendMailApiPostResponse
     * @throws \WlSdk\WlSdkException On non-2xx HTTP response.
     * @throws \RuntimeException On network or cURL error.
     */
    public function post(): SendMailApiPostResponse
    {
        return new SendMailApiPostResponse($this->client->request('/Wl/AiAgent/Link/SendMail.json', $this->params(), 'POST'));
    }

    private function params(): array
    {
        return array_filter(
            [
            'id_purchase_item' => $this->id_purchase_item,
            'id_service' => $this->id_service,
            'k_business' => $this->k_business,
            'k_id' => $this->k_id,
            'text_action' => $this->text_action,
            'uid' => $this->uid,
            ],
            static fn($v) => $v !== null
        );
    }
}
