<?php
namespace WlSdk\Wl\AiAgent\Link;

use WlSdk\WlSdkClient;

/**
 * Sends an AI agent link action email (booking or purchase) to the specified user.
 */
class SendMailApi
{
    /**
     * Custom rules for mapping API error status codes to HTTP status codes.

By default the API always returns HTTP 200, even when the response contains an error. Setting this header enables error-to-HTTP-code conversion: when the response status matches a rule, the corresponding 4xx code is returned instead of 200.

Format: comma-separated entries of `{4xx_code} {pattern}[, ...]`. Pattern syntax:
- `status` - exact status match.
- `-suffix` - status ends with `-suffix`.
- `-part-` - status contains `-part-`.
- `prefix-` - status starts with `prefix-`.
- `-` - catch-all for any non-ok status that did not match any other rule.

The special entry `default` (no HTTP code prefix) expands to the built-in ruleset at that position: `400 -`, `403 -access access access-`, `404 -nx`. Rules listed before `default` override the built-in ones; rules after are fallbacks. Example: `401 access,403 access-,404 -nx,default`.

Only standard 4xx codes are accepted.
     *
     * @var string|null
     */
    public ?string $X-Error-Rules = null;

    /**
     * Purchase item ID. Required if `text_action` is 'purchase'.

One of the [RsPurchaseItemSid](#/components/schemas/RsPurchaseItemSid) constants.
     *
     * @var int|null
     */
    public ?int $id_purchase_item = null;

    /**
     * Service ID. Required if `text_action` is 'booking'.
     *
     * @var int|null
     */
    public ?int $id_service = null;

    /**
     * Business key. Required.
     *
     * @var string|null
     */
    public ?string $k_business = null;

    /**
     * Unique identifier for the link.
     *
     * @var string|null
     */
    public ?string $k_id = null;

    /**
     * Action type. Must be 'purchase' or 'booking'.
     *
     * @var string|null
     */
    public ?string $text_action = null;

    /**
     * User ID. Required.
     *
     * @var string|null
     */
    public ?string $uid = null;

    /** @var WlSdkClient */
    private $client;

    public function __construct(WlSdkClient $client)
    {
        $this->client = $client;
    }

    /**
     * Sends an AI agent link action email (booking or purchase) to the specified user.
     *
     * Triggers the email that the AI agent sends when a client clicks a booking or purchase link
     *  generated by the AI agent chat. Requires the business to have an active AI agent subscription;
     *  the action type determines which notification template is used and which service or purchase
     *  item is referenced in the email body.
     *
     * @return array Parsed JSON response data.
     * @throws \WlSdk\WlSdkException On non-2xx HTTP response.
     * @throws \RuntimeException On network or cURL error.
     */
    public function post(): array
    {
        return $this->client->request('/Wl/AiAgent/Link/SendMail.json', $this->params(), 'POST');
    }

    private function params(): array
    {
        return array_filter(
            [
            'X-Error-Rules' => $this->X-Error-Rules,
            'id_purchase_item' => $this->id_purchase_item,
            'id_service' => $this->id_service,
            'k_business' => $this->k_business,
            'k_id' => $this->k_id,
            'text_action' => $this->text_action,
            'uid' => $this->uid,
            ],
            static fn($v) => $v !== null
        );
    }
}
