<?php
/**
 * WellnessLiving PHP SDK ({{CHANNEL}})
 * Spec version: {{SPEC_VERSION}}
 * Build date:   {{BUILD_DATE}}
 * Endpoints:    {{ENDPOINT_COUNT}}
 *
 * Auto-generated from:
 * https://github.com/wellnessliving/openapi/blob/main/{{CHANNEL}}/openapi.yaml
 *
 * Requirements: PHP 7.4+, ext-curl, ext-json
 *
 * Usage:
 *   require 'wl-sdk.php';
 *   $client = new WlSdk(['token' => 'YOUR_JWT_TOKEN']);
 *   $result = $client->coreRequestExample(['i_argument' => 1]);
 *
 * Do not edit this file manually.
 * Run `composer run generate` to regenerate from the latest spec.
 */

/**
 * Thrown when the WellnessLiving API returns a non-2xx HTTP response.
 */
class WlSdkException extends \RuntimeException
{
    /**
     * @var array|null Parsed JSON response body, or null if the body was not valid JSON.
     */
    public $data;

    /**
     * @param string $message Human-readable error description.
     * @param int $status HTTP status code.
     * @param array|null $data Parsed JSON response body.
     */
    public function __construct(string $message, int $status, $data = null)
    {
        parent::__construct($message, $status);
        $this->data = $data;
    }
}

/**
 * WellnessLiving API PHP client.
 *
 * Auto-generated from the OpenAPI specification.
 * Do not edit this file manually - run `composer run generate` to regenerate.
 *
 * @see https://github.com/wellnessliving/wl-sdk-php-v2
 * @see https://developers.wellnessliving.com
 */
class WlSdk
{
    /**
     * SDK channel identifier ('stable' or 'dev').
     */
    public const CHANNEL = '{{CHANNEL}}';

    /**
     * OpenAPI specification version used to generate this SDK.
     */
    public const SPEC_VERSION = '{{SPEC_VERSION}}';

    /**
     * @var string|null JWT Bearer token for authentication.
     */
    private $token;

    /**
     * @var string API server base URL (no trailing slash).
     */
    private $base_url;

    /**
     * @var int Request timeout in seconds.
     */
    private $timeout;

    /**
     * @param array $options Configuration options:
     *   - string|null token: JWT Bearer token for authentication.
     *   - string base_url: API server base URL.
     *     Default: 'https://staging.wellnessliving.com' (US data center).
     *     Use 'https://demo.wellnessliving.com' for the Australia data center.
     *   - int timeout: Request timeout in seconds. Default: 30.
     * @throws \InvalidArgumentException If options is not a valid array.
     */
    public function __construct(array $options)
    {
        $this->token = isset($options['token']) ? (string)$options['token'] : null;
        $this->base_url = rtrim(
            isset($options['base_url']) ? (string)$options['base_url'] : 'https://staging.wellnessliving.com',
            '/'
        );
        $timeout = isset($options['timeout']) ? (int)$options['timeout'] : 30;
        $this->timeout = $timeout > 0 ? $timeout : 30;
    }

    /**
     * Sends an HTTP request to the API.
     *
     * GET and HEAD requests encode params as a query string.
     * All other methods encode params as application/x-www-form-urlencoded body.
     *
     * @param string $path Endpoint path (e.g., '/Core/Request/Example.json').
     * @param array $params Query parameters (GET/HEAD) or form fields (POST/PUT/PATCH/DELETE).
     * @param string $method HTTP method: 'GET', 'POST', 'PUT', 'PATCH', 'DELETE', etc.
     * @return array Parsed JSON response data.
     * @throws \WlSdkException If the API returns a non-2xx HTTP status.
     * @throws \RuntimeException If the cURL request itself fails (network error, timeout, etc.).
     */
    public function request(string $path, array $params = [], string $method = 'GET'): array
    {
        $method = strtoupper($method);
        $url = $this->base_url . $path;

        $ch = curl_init();
        $headers = ['Accept: application/json'];

        if ($this->token !== null) {
            $headers[] = 'Authorization: Bearer ' . $this->token;
        }

        if ($method === 'GET' || $method === 'HEAD') {
            if (!empty($params)) {
                $url .= '?' . http_build_query($params);
            }
        } else {
            curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($params));
            $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        }

        if ($method === 'POST') {
            curl_setopt($ch, CURLOPT_POST, true);
        } elseif ($method !== 'GET') {
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
        }

        curl_setopt_array($ch, [
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HTTPHEADER => $headers,
            CURLOPT_TIMEOUT => $this->timeout,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_USERAGENT => 'wl-sdk-php/' . self::SPEC_VERSION,
        ]);

        $body = curl_exec($ch);
        $status = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlError = curl_error($ch);
        curl_close($ch);

        if ($body === false) {
            throw new \RuntimeException('WlSdk request failed: ' . $curlError);
        }

        $data = json_decode($body, true);

        if ($status < 200 || $status >= 300) {
            $message = 'WlSdk: HTTP ' . $status;
            if (is_array($data) && isset($data['message']) && is_string($data['message'])) {
                $message .= ': ' . $data['message'];
            }
            throw new \WlSdkException($message, $status, is_array($data) ? $data : null);
        }

        return is_array($data) ? $data : [];
    }

{{GENERATED_METHODS}}
}
