<?php

namespace WlSdk\Wl\ClassPass;

class AppointmentAttendanceGetRequest
{
    /**
     * Appointment reservation identifier generated by `Classpass`.
     *
     * @var string|null
     */
    public ?string $s_appointment_id = null;

    /**
     * Partner ID.
     *
     * @var string|null
     */
    public ?string $s_partner_id = null;

    /**
     * Venue ID.
     *
     * @var string|null
     */
    public ?string $s_venue_id = null;

    public function params(): array
    {
        return array_filter(
            [
            's_appointment_id' => $this->s_appointment_id,
            's_partner_id' => $this->s_partner_id,
            's_venue_id' => $this->s_venue_id,
            ],
            static fn ($v) => $v !== null
        );
    }
}
