<?php
namespace WlSdk\Wl\AiAgent\Link;

use WlSdk\WlSdkClient;

/**
 * Sends an AI agent link action email (booking or purchase) to the specified user.
 */
class SendMailPost
{
    /** @var WlSdkClient */
    private $client;

    public function __construct(WlSdkClient $client)
    {
        $this->client = $client;
    }

    /**
     * Sends an AI agent link action email (booking or purchase) to the specified user.
     *
     * Triggers the email that the AI agent sends when a client clicks a booking or purchase link
     *  generated by the AI agent chat. Requires the business to have an active AI agent subscription;
     *  the action type determines which notification template is used and which service or purchase
     *  item is referenced in the email body.
     *
     * @return SendMailPostResponse
     * @throws \WlSdk\WlSdkException On non-2xx HTTP response.
     * @throws \RuntimeException On network or cURL error.
     */
    public function post(SendMailPostRequest $request): SendMailPostResponse
    {
        return new SendMailPostResponse($this->client->request('/Wl/AiAgent/Link/SendMail.json', $request->params(), 'POST'));
    }
}
