<?php

namespace WlSdk\Wl\AiAgent\Phone;

class CallReceivedPostRequest
{
    /**
     * How the call ended. Required.
     *
     * @var int|null
     * @see \WlSdk\Wl\AiAgent\Phone\CallOutcomeEnum
     */
    public ?int $id_call_outcome = null;

    /**
     * Business key. Required.
     *
     * @var string|null
     */
    public ?string $k_business = null;

    /**
     * Short summary of the call generated by CAASI. Used in the email notification only. Optional.
     *
     * @var string|null
     */
    public ?string $text_call_summary = null;

    /**
     * The caller's name, if identified. Optional.
     *
     * @var string|null
     */
    public ?string $text_caller_name = null;

    /**
     * The caller's phone number. Optional.
     *
     * @var string|null
     */
    public ?string $text_caller_phone = null;

    /**
     * URL to view the conversation between the caller and CAASI (for email). Optional.
     *
     * @var string|null
     */
    public ?string $url_view_conversation_link = null;

    /**
     * URL to view the conversation, in an SMS-safe format. Optional.
     *
     * @var string|null
     */
    public ?string $url_view_conversation_link_sms = null;

    public function params(): array
    {
        return array_filter(
            [
            'id_call_outcome' => $this->id_call_outcome,
            'k_business' => $this->k_business,
            'text_call_summary' => $this->text_call_summary,
            'text_caller_name' => $this->text_caller_name,
            'text_caller_phone' => $this->text_caller_phone,
            'url_view_conversation_link' => $this->url_view_conversation_link,
            'url_view_conversation_link_sms' => $this->url_view_conversation_link_sms,
            ],
            static fn ($v) => $v !== null
        );
    }
}
